# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_menu_staff.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 800)
        Dialog.setMinimumSize(QtCore.QSize(1200, 800))
        Dialog.setMaximumSize(QtCore.QSize(1200, 800))
        Dialog.setStyleSheet("QDialog#Dialog{\n"
"background-color:  rgb(125, 125, 125);\n"
"}\n"
"*{\n"
"    border : none;\n"
"    color: white;\n"
"    font: 75 10pt \"Consolas\";\n"
"}\n"
"QToolBox::tab{\n"
"    border-radius:5px;\n"
"    text-align:left;\n"
"}\n"
"\n"
"QToolBox{\n"
"    text-align: left;\n"
"    color: white;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.slide_menu_container = QtWidgets.QFrame(Dialog)
        self.slide_menu_container.setMaximumSize(QtCore.QSize(250, 16777215))
        self.slide_menu_container.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.slide_menu_container.setStyleSheet("background-color:rgb(38, 90, 92)")
        self.slide_menu_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.slide_menu_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.slide_menu_container.setObjectName("slide_menu_container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.slide_menu_container)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.slide_menu_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.header = QtWidgets.QFrame(self.frame_2)
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_6 = QtWidgets.QPushButton(self.header)
        self.pushButton_6.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../.designer/backup/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_8.addWidget(self.pushButton_6)
        self.label_4 = QtWidgets.QLabel(self.header)
        self.label_4.setStyleSheet("font: 500 italic 20pt \"Ubuntu\";\n"
"color : rgb(221, 221, 221);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.verticalLayout_6.addWidget(self.header, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.side_menu_menu = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.side_menu_menu.sizePolicy().hasHeightForWidth())
        self.side_menu_menu.setSizePolicy(sizePolicy)
        self.side_menu_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.side_menu_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_menu_menu.setObjectName("side_menu_menu")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.side_menu_menu)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.side_box = QtWidgets.QToolBox(self.side_menu_menu)
        self.side_box.setStyleSheet("font: 700 15pt \"Ubuntu\";")
        self.side_box.setObjectName("side_box")
        self.app_page = QtWidgets.QWidget()
        self.app_page.setGeometry(QtCore.QRect(0, 0, 250, 594))
        self.app_page.setObjectName("app_page")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.app_page)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame = QtWidgets.QFrame(self.app_page)
        self.frame.setMinimumSize(QtCore.QSize(20, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_13.addWidget(self.frame)
        self.app_list = QtWidgets.QListWidget(self.app_page)
        self.app_list.setStyleSheet("")
        self.app_list.setObjectName("app_list")
        self.horizontalLayout_13.addWidget(self.app_list)
        self.side_box.addItem(self.app_page, "")
        self.report_page = QtWidgets.QWidget()
        self.report_page.setGeometry(QtCore.QRect(0, 0, 250, 594))
        self.report_page.setObjectName("report_page")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.report_page)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_3 = QtWidgets.QFrame(self.report_page)
        self.frame_3.setMinimumSize(QtCore.QSize(20, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(20, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_12.addWidget(self.frame_3)
        self.rerport_box = QtWidgets.QToolBox(self.report_page)
        self.rerport_box.setObjectName("rerport_box")
        self.new_report_page = QtWidgets.QWidget()
        self.new_report_page.setGeometry(QtCore.QRect(0, 0, 230, 520))
        self.new_report_page.setObjectName("new_report_page")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.new_report_page)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_5 = QtWidgets.QFrame(self.new_report_page)
        self.frame_5.setMinimumSize(QtCore.QSize(20, 0))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_14.addWidget(self.frame_5)
        self.report_list = QtWidgets.QListWidget(self.new_report_page)
        self.report_list.setObjectName("report_list")
        self.horizontalLayout_14.addWidget(self.report_list)
        self.rerport_box.addItem(self.new_report_page, "")
        self.old_report_page = QtWidgets.QWidget()
        self.old_report_page.setGeometry(QtCore.QRect(0, 0, 89, 69))
        self.old_report_page.setObjectName("old_report_page")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.old_report_page)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame_6 = QtWidgets.QFrame(self.old_report_page)
        self.frame_6.setMinimumSize(QtCore.QSize(20, 0))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_15.addWidget(self.frame_6)
        self.old_report_list = QtWidgets.QListWidget(self.old_report_page)
        self.old_report_list.setStyleSheet("")
        self.old_report_list.setObjectName("old_report_list")
        self.horizontalLayout_15.addWidget(self.old_report_list)
        self.rerport_box.addItem(self.old_report_page, "")
        self.horizontalLayout_12.addWidget(self.rerport_box)
        self.side_box.addItem(self.report_page, "")
        self.bug_page = QtWidgets.QWidget()
        self.bug_page.setGeometry(QtCore.QRect(0, 0, 250, 594))
        self.bug_page.setObjectName("bug_page")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.bug_page)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_4 = QtWidgets.QFrame(self.bug_page)
        self.frame_4.setMinimumSize(QtCore.QSize(20, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_9.addWidget(self.frame_4)
        self.bug_list = QtWidgets.QListWidget(self.bug_page)
        self.bug_list.setObjectName("bug_list")
        self.horizontalLayout_9.addWidget(self.bug_list)
        self.side_box.addItem(self.bug_page, "")
        self.verticalLayout_7.addWidget(self.side_box)
        self.verticalLayout_6.addWidget(self.side_menu_menu)
        self.footer = QtWidgets.QFrame(self.frame_2)
        self.footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer.setObjectName("footer")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.footer)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.signout_button = QtWidgets.QPushButton(self.footer)
        self.signout_button.setStyleSheet("font: 20pt \"Consolas\";\n"
"color : rgb(221, 221, 221);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.signout_button.setIcon(icon1)
        self.signout_button.setIconSize(QtCore.QSize(30, 30))
        self.signout_button.setObjectName("signout_button")
        self.verticalLayout_4.addWidget(self.signout_button, 0, QtCore.Qt.AlignLeft)
        self.exit_button = QtWidgets.QPushButton(self.footer)
        self.exit_button.setStyleSheet("font: 20pt \"Consolas\";\n"
"color : rgb(221, 221, 221);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_button.setIcon(icon2)
        self.exit_button.setIconSize(QtCore.QSize(30, 30))
        self.exit_button.setObjectName("exit_button")
        self.verticalLayout_4.addWidget(self.exit_button, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_6.addWidget(self.footer, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignBottom)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.slide_menu_container)
        self.main_menu_container = QtWidgets.QFrame(Dialog)
        self.main_menu_container.setStyleSheet("background-color:rgb(63, 123, 112)")
        self.main_menu_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_menu_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_menu_container.setObjectName("main_menu_container")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_menu_container)
        self.verticalLayout.setContentsMargins(3, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_frame = QtWidgets.QFrame(self.main_menu_container)
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.header_0 = QtWidgets.QFrame(self.header_frame)
        self.header_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_0.setObjectName("header_0")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.header_0)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.menu_button = QtWidgets.QPushButton(self.header_0)
        self.menu_button.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.menu_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_button.setIcon(icon3)
        self.menu_button.setIconSize(QtCore.QSize(25, 25))
        self.menu_button.setObjectName("menu_button")
        self.horizontalLayout_7.addWidget(self.menu_button, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.horizontalLayout_5.addWidget(self.header_0, 0, QtCore.Qt.AlignLeft)
        self.header_1 = QtWidgets.QFrame(self.header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_1.sizePolicy().hasHeightForWidth())
        self.header_1.setSizePolicy(sizePolicy)
        self.header_1.setMinimumSize(QtCore.QSize(0, 0))
        self.header_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_1.setObjectName("header_1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.header_1)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_10 = QtWidgets.QFrame(self.header_1)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_6.addWidget(self.frame_10)
        self.horizontalLayout_5.addWidget(self.header_1)
        self.header_2 = QtWidgets.QFrame(self.header_frame)
        self.header_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_2.setObjectName("header_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.refresh_button = QtWidgets.QPushButton(self.header_2)
        self.refresh_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/refresh-cw.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh_button.setIcon(icon4)
        self.refresh_button.setIconSize(QtCore.QSize(20, 20))
        self.refresh_button.setObjectName("refresh_button")
        self.horizontalLayout_2.addWidget(self.refresh_button)
        self.horizontalLayout_5.addWidget(self.header_2)
        self.verticalLayout.addWidget(self.header_frame)
        self.main_menu_content = QtWidgets.QFrame(self.main_menu_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_menu_content.sizePolicy().hasHeightForWidth())
        self.main_menu_content.setSizePolicy(sizePolicy)
        self.main_menu_content.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.main_menu_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_menu_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_menu_content.setObjectName("main_menu_content")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.main_menu_content)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pager = QtWidgets.QStackedWidget(self.main_menu_content)
        self.pager.setObjectName("pager")
        self.test_page_1 = QtWidgets.QWidget()
        self.test_page_1.setObjectName("test_page_1")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.test_page_1)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 0, 951, 721))
        self.plainTextEdit.setStyleSheet("font: 700 20pt \"Ubuntu\";\n"
"color : white;")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pager.addWidget(self.test_page_1)
        self.test_page_2 = QtWidgets.QWidget()
        self.test_page_2.setObjectName("test_page_2")
        self.label_5 = QtWidgets.QLabel(self.test_page_2)
        self.label_5.setGeometry(QtCore.QRect(0, 10, 191, 41))
        self.label_5.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color: rgb(17, 60, 74);")
        self.label_5.setObjectName("label_5")
        self.create_bug_button = QtWidgets.QPushButton(self.test_page_2)
        self.create_bug_button.setGeometry(QtCore.QRect(200, 670, 171, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_bug_button.sizePolicy().hasHeightForWidth())
        self.create_bug_button.setSizePolicy(sizePolicy)
        self.create_bug_button.setStyleSheet("background-color: rgb(246, 114, 128);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 20px;\n"
"border-color: white;\n"
"padding: 2px;\n"
"font: 700 20pt \"Ubuntu\";\n"
"color : white;")
        self.create_bug_button.setObjectName("create_bug_button")
        self.report_description_box = QtWidgets.QPlainTextEdit(self.test_page_2)
        self.report_description_box.setEnabled(False)
        self.report_description_box.setGeometry(QtCore.QRect(0, 170, 821, 451))
        self.report_description_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.report_description_box.setObjectName("report_description_box")
        self.label_6 = QtWidgets.QLabel(self.test_page_2)
        self.label_6.setGeometry(QtCore.QRect(0, 110, 221, 51))
        self.label_6.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color:rgb(17, 60, 74);")
        self.label_6.setObjectName("label_6")
        self.report_title_box = QtWidgets.QPlainTextEdit(self.test_page_2)
        self.report_title_box.setEnabled(False)
        self.report_title_box.setGeometry(QtCore.QRect(0, 50, 431, 51))
        self.report_title_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.report_title_box.setObjectName("report_title_box")
        self.delete_report_button = QtWidgets.QPushButton(self.test_page_2)
        self.delete_report_button.setGeometry(QtCore.QRect(0, 670, 191, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_report_button.sizePolicy().hasHeightForWidth())
        self.delete_report_button.setSizePolicy(sizePolicy)
        self.delete_report_button.setStyleSheet("background-color: rgb(246, 114, 128);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 18px;\n"
"border-color: white;\n"
"padding: 2px;\n"
"font: 700 20pt \"Ubuntu\";\n"
"color : white;")
        self.delete_report_button.setObjectName("delete_report_button")
        self.pager.addWidget(self.test_page_2)
        self.test_page_3 = QtWidgets.QWidget()
        self.test_page_3.setObjectName("test_page_3")
        self.label_7 = QtWidgets.QLabel(self.test_page_3)
        self.label_7.setGeometry(QtCore.QRect(0, 10, 91, 41))
        self.label_7.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color: rgb(17, 60, 74);")
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(self.test_page_3)
        self.label_10.setGeometry(QtCore.QRect(0, 110, 221, 51))
        self.label_10.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color:rgb(17, 60, 74);")
        self.label_10.setObjectName("label_10")
        self.bug_title_box = QtWidgets.QPlainTextEdit(self.test_page_3)
        self.bug_title_box.setEnabled(False)
        self.bug_title_box.setGeometry(QtCore.QRect(0, 50, 431, 51))
        self.bug_title_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.bug_title_box.setObjectName("bug_title_box")
        self.bug_description_box = QtWidgets.QPlainTextEdit(self.test_page_3)
        self.bug_description_box.setEnabled(False)
        self.bug_description_box.setGeometry(QtCore.QRect(0, 170, 861, 261))
        self.bug_description_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.bug_description_box.setObjectName("bug_description_box")
        self.bug_serverity_box = QtWidgets.QPlainTextEdit(self.test_page_3)
        self.bug_serverity_box.setEnabled(False)
        self.bug_serverity_box.setGeometry(QtCore.QRect(0, 490, 221, 51))
        self.bug_serverity_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.bug_serverity_box.setPlainText("")
        self.bug_serverity_box.setPlaceholderText("")
        self.bug_serverity_box.setObjectName("bug_serverity_box")
        self.label_11 = QtWidgets.QLabel(self.test_page_3)
        self.label_11.setGeometry(QtCore.QRect(0, 440, 181, 41))
        self.label_11.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color: rgb(17, 60, 74);")
        self.label_11.setObjectName("label_11")
        self.bug_status_box = QtWidgets.QPlainTextEdit(self.test_page_3)
        self.bug_status_box.setEnabled(False)
        self.bug_status_box.setGeometry(QtCore.QRect(0, 600, 221, 51))
        self.bug_status_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.bug_status_box.setPlaceholderText("")
        self.bug_status_box.setObjectName("bug_status_box")
        self.label_12 = QtWidgets.QLabel(self.test_page_3)
        self.label_12.setGeometry(QtCore.QRect(0, 550, 131, 41))
        self.label_12.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color: rgb(17, 60, 74);")
        self.label_12.setObjectName("label_12")
        self.update_bug_button = QtWidgets.QPushButton(self.test_page_3)
        self.update_bug_button.setGeometry(QtCore.QRect(0, 670, 171, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_bug_button.sizePolicy().hasHeightForWidth())
        self.update_bug_button.setSizePolicy(sizePolicy)
        self.update_bug_button.setStyleSheet("background-color: rgb(246, 114, 128);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 20px;\n"
"border-color: white;\n"
"padding: 2px;\n"
"font: 700 20pt \"Ubuntu\";\n"
"color : white;")
        self.update_bug_button.setObjectName("update_bug_button")
        self.pager.addWidget(self.test_page_3)
        self.change_bug_page = QtWidgets.QWidget()
        self.change_bug_page.setObjectName("change_bug_page")
        self.label_9 = QtWidgets.QLabel(self.change_bug_page)
        self.label_9.setGeometry(QtCore.QRect(0, 10, 91, 41))
        self.label_9.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color: rgb(17, 60, 74);")
        self.label_9.setObjectName("label_9")
        self.confirm_update_bug_button = QtWidgets.QPushButton(self.change_bug_page)
        self.confirm_update_bug_button.setGeometry(QtCore.QRect(140, 670, 131, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confirm_update_bug_button.sizePolicy().hasHeightForWidth())
        self.confirm_update_bug_button.setSizePolicy(sizePolicy)
        self.confirm_update_bug_button.setStyleSheet("background-color: rgb(246, 114, 128);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 20px;\n"
"border-color: white;\n"
"padding: 2px;\n"
"font: 700 20pt \"Ubuntu\";\n"
"color : white;")
        self.confirm_update_bug_button.setObjectName("confirm_update_bug_button")
        self.update_bug_description_box = QtWidgets.QPlainTextEdit(self.change_bug_page)
        self.update_bug_description_box.setEnabled(True)
        self.update_bug_description_box.setGeometry(QtCore.QRect(0, 170, 861, 261))
        self.update_bug_description_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.update_bug_description_box.setObjectName("update_bug_description_box")
        self.label_13 = QtWidgets.QLabel(self.change_bug_page)
        self.label_13.setGeometry(QtCore.QRect(0, 550, 131, 41))
        self.label_13.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color: rgb(17, 60, 74);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.change_bug_page)
        self.label_14.setGeometry(QtCore.QRect(0, 440, 181, 41))
        self.label_14.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color: rgb(17, 60, 74);")
        self.label_14.setObjectName("label_14")
        self.update_bug_title_box = QtWidgets.QPlainTextEdit(self.change_bug_page)
        self.update_bug_title_box.setEnabled(True)
        self.update_bug_title_box.setGeometry(QtCore.QRect(0, 50, 431, 51))
        self.update_bug_title_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.update_bug_title_box.setObjectName("update_bug_title_box")
        self.label_15 = QtWidgets.QLabel(self.change_bug_page)
        self.label_15.setGeometry(QtCore.QRect(0, 110, 221, 51))
        self.label_15.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color:rgb(17, 60, 74);")
        self.label_15.setObjectName("label_15")
        self.delete_bug_button = QtWidgets.QPushButton(self.change_bug_page)
        self.delete_bug_button.setGeometry(QtCore.QRect(0, 670, 131, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_bug_button.sizePolicy().hasHeightForWidth())
        self.delete_bug_button.setSizePolicy(sizePolicy)
        self.delete_bug_button.setStyleSheet("background-color: rgb(246, 114, 128);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 20px;\n"
"border-color: white;\n"
"padding: 2px;\n"
"font: 700 20pt \"Ubuntu\";\n"
"color : white;")
        self.delete_bug_button.setObjectName("delete_bug_button")
        self.update_bug_serverity_box = QtWidgets.QComboBox(self.change_bug_page)
        self.update_bug_serverity_box.setGeometry(QtCore.QRect(0, 490, 171, 51))
        self.update_bug_serverity_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:10px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.update_bug_serverity_box.setObjectName("update_bug_serverity_box")
        self.update_bug_serverity_box.addItem("")
        self.update_bug_serverity_box.addItem("")
        self.update_bug_serverity_box.addItem("")
        self.update_bug_serverity_box.addItem("")
        self.update_bug_serverity_box.addItem("")
        self.update_bug_status_box = QtWidgets.QComboBox(self.change_bug_page)
        self.update_bug_status_box.setGeometry(QtCore.QRect(0, 600, 171, 51))
        self.update_bug_status_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:10px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.update_bug_status_box.setObjectName("update_bug_status_box")
        self.update_bug_status_box.addItem("")
        self.update_bug_status_box.addItem("")
        self.update_bug_status_box.addItem("")
        self.update_bug_status_box.addItem("")
        self.cancel_update_bug_button = QtWidgets.QPushButton(self.change_bug_page)
        self.cancel_update_bug_button.setGeometry(QtCore.QRect(280, 670, 131, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_update_bug_button.sizePolicy().hasHeightForWidth())
        self.cancel_update_bug_button.setSizePolicy(sizePolicy)
        self.cancel_update_bug_button.setStyleSheet("background-color: rgb(246, 114, 128);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 20px;\n"
"border-color: white;\n"
"padding: 2px;\n"
"font: 700 20pt \"Ubuntu\";\n"
"color : white;")
        self.cancel_update_bug_button.setObjectName("cancel_update_bug_button")
        self.pager.addWidget(self.change_bug_page)
        self.create_bug_page = QtWidgets.QWidget()
        self.create_bug_page.setObjectName("create_bug_page")
        self.create_bug_serverity_box = QtWidgets.QComboBox(self.create_bug_page)
        self.create_bug_serverity_box.setGeometry(QtCore.QRect(0, 490, 171, 51))
        self.create_bug_serverity_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:10px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.create_bug_serverity_box.setObjectName("create_bug_serverity_box")
        self.create_bug_serverity_box.addItem("")
        self.create_bug_serverity_box.addItem("")
        self.create_bug_serverity_box.addItem("")
        self.create_bug_serverity_box.addItem("")
        self.create_bug_serverity_box.addItem("")
        self.label_16 = QtWidgets.QLabel(self.create_bug_page)
        self.label_16.setGeometry(QtCore.QRect(0, 110, 221, 51))
        self.label_16.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color:rgb(17, 60, 74);")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.create_bug_page)
        self.label_17.setGeometry(QtCore.QRect(0, 10, 91, 41))
        self.label_17.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color: rgb(17, 60, 74);")
        self.label_17.setObjectName("label_17")
        self.create_bug_status_box = QtWidgets.QComboBox(self.create_bug_page)
        self.create_bug_status_box.setGeometry(QtCore.QRect(0, 600, 171, 51))
        self.create_bug_status_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:10px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.create_bug_status_box.setObjectName("create_bug_status_box")
        self.create_bug_status_box.addItem("")
        self.create_bug_status_box.addItem("")
        self.create_bug_status_box.addItem("")
        self.create_bug_status_box.addItem("")
        self.cancel_create_bug_button = QtWidgets.QPushButton(self.create_bug_page)
        self.cancel_create_bug_button.setGeometry(QtCore.QRect(170, 670, 171, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_create_bug_button.sizePolicy().hasHeightForWidth())
        self.cancel_create_bug_button.setSizePolicy(sizePolicy)
        self.cancel_create_bug_button.setStyleSheet("background-color: rgb(246, 114, 128);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 20px;\n"
"border-color: white;\n"
"padding: 2px;\n"
"font: 700 20pt \"Ubuntu\";\n"
"color : white;")
        self.cancel_create_bug_button.setObjectName("cancel_create_bug_button")
        self.confirm_create_bug_button = QtWidgets.QPushButton(self.create_bug_page)
        self.confirm_create_bug_button.setGeometry(QtCore.QRect(0, 670, 161, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confirm_create_bug_button.sizePolicy().hasHeightForWidth())
        self.confirm_create_bug_button.setSizePolicy(sizePolicy)
        self.confirm_create_bug_button.setStyleSheet("background-color: rgb(246, 114, 128);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 20px;\n"
"border-color: white;\n"
"padding: 2px;\n"
"font: 700 20pt \"Ubuntu\";\n"
"color : white;")
        self.confirm_create_bug_button.setObjectName("confirm_create_bug_button")
        self.label_18 = QtWidgets.QLabel(self.create_bug_page)
        self.label_18.setGeometry(QtCore.QRect(0, 550, 131, 41))
        self.label_18.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color: rgb(17, 60, 74);")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.create_bug_page)
        self.label_19.setGeometry(QtCore.QRect(0, 440, 181, 41))
        self.label_19.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color: rgb(17, 60, 74);")
        self.label_19.setObjectName("label_19")
        self.create_bug_description_box = QtWidgets.QPlainTextEdit(self.create_bug_page)
        self.create_bug_description_box.setEnabled(True)
        self.create_bug_description_box.setGeometry(QtCore.QRect(0, 170, 861, 261))
        self.create_bug_description_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.create_bug_description_box.setObjectName("create_bug_description_box")
        self.create_bug_title_box = QtWidgets.QPlainTextEdit(self.create_bug_page)
        self.create_bug_title_box.setEnabled(True)
        self.create_bug_title_box.setGeometry(QtCore.QRect(0, 50, 431, 51))
        self.create_bug_title_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.create_bug_title_box.setObjectName("create_bug_title_box")
        self.pager.addWidget(self.create_bug_page)
        self.horizontalLayout_10.addWidget(self.pager)
        self.verticalLayout.addWidget(self.main_menu_content)
        self.footer_frame = QtWidgets.QFrame(self.main_menu_container)
        self.footer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer_frame.setObjectName("footer_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.footer_frame)
        self.horizontalLayout_3.setContentsMargins(0, 4, 0, 2)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_8 = QtWidgets.QFrame(self.footer_frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_8)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_3.addWidget(self.frame_8)
        self.frame_7 = QtWidgets.QFrame(self.footer_frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_7)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2, 0, QtCore.Qt.AlignRight)
        self.website_button = QtWidgets.QPushButton(self.frame_7)
        self.website_button.setStyleSheet("color:blue;")
        self.website_button.setObjectName("website_button")
        self.horizontalLayout_4.addWidget(self.website_button, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_3.addWidget(self.frame_7)
        self.frame_9 = QtWidgets.QFrame(self.footer_frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_11.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_3 = QtWidgets.QLabel(self.frame_9)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_11.addWidget(self.label_3, 0, QtCore.Qt.AlignRight)
        self.email_button = QtWidgets.QPushButton(self.frame_9)
        self.email_button.setStyleSheet("color:blue;")
        self.email_button.setObjectName("email_button")
        self.horizontalLayout_11.addWidget(self.email_button)
        self.horizontalLayout_3.addWidget(self.frame_9)
        self.verticalLayout.addWidget(self.footer_frame, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.main_menu_container)

        self.retranslateUi(Dialog)
        self.side_box.setCurrentIndex(1)
        self.rerport_box.setCurrentIndex(0)
        self.pager.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "Bug Tracker"))
        self.side_box.setItemText(self.side_box.indexOf(self.app_page), _translate("Dialog", "➤ App"))
        self.rerport_box.setItemText(self.rerport_box.indexOf(self.new_report_page), _translate("Dialog", "➤ New Report"))
        self.rerport_box.setItemText(self.rerport_box.indexOf(self.old_report_page), _translate("Dialog", "➤ Old report"))
        self.side_box.setItemText(self.side_box.indexOf(self.report_page), _translate("Dialog", "➤ Report"))
        self.side_box.setItemText(self.side_box.indexOf(self.bug_page), _translate("Dialog", "➤ Bug"))
        self.signout_button.setText(_translate("Dialog", "Sign Out"))
        self.exit_button.setText(_translate("Dialog", "Exit "))
        self.plainTextEdit.setPlainText(_translate("Dialog", "For starter :\n"
"    Step 1: Open the side menu\n"
"    Step 2: Select an App\n"
"        Step 2.1: Select a Report\n"
"            Step 2.1.1: Read Report/Create Bug/Delete Report\n"
"        Step 2.2: Select a Bug\n"
"            Step 2.2.2: Read Bug/Update Bug/Delete Bug\n"
"\n"
""))
        self.label_5.setText(_translate("Dialog", "Problem"))
        self.create_bug_button.setText(_translate("Dialog", "Create Bug"))
        self.report_description_box.setPlaceholderText(_translate("Dialog", "\"None\""))
        self.label_6.setText(_translate("Dialog", "Description"))
        self.report_title_box.setPlaceholderText(_translate("Dialog", "Select a report first"))
        self.delete_report_button.setText(_translate("Dialog", "Delete Report"))
        self.label_7.setText(_translate("Dialog", "Title"))
        self.label_10.setText(_translate("Dialog", "Description"))
        self.bug_title_box.setPlaceholderText(_translate("Dialog", "Select a bug first"))
        self.bug_description_box.setPlaceholderText(_translate("Dialog", "\"None\""))
        self.label_11.setText(_translate("Dialog", "Serverity"))
        self.label_12.setText(_translate("Dialog", "Status"))
        self.update_bug_button.setText(_translate("Dialog", "Update Bug"))
        self.label_9.setText(_translate("Dialog", "Title"))
        self.confirm_update_bug_button.setText(_translate("Dialog", "Update"))
        self.update_bug_description_box.setPlainText(_translate("Dialog", "Date : \n"
"Tested by :\n"
"Cause by :"))
        self.update_bug_description_box.setPlaceholderText(_translate("Dialog", "Enter the description here please"))
        self.label_13.setText(_translate("Dialog", "Status"))
        self.label_14.setText(_translate("Dialog", "Serverity"))
        self.update_bug_title_box.setPlaceholderText(_translate("Dialog", "Please do not leave blank"))
        self.label_15.setText(_translate("Dialog", "Description"))
        self.delete_bug_button.setText(_translate("Dialog", "Delete"))
        self.update_bug_serverity_box.setItemText(0, _translate("Dialog", "Small"))
        self.update_bug_serverity_box.setItemText(1, _translate("Dialog", "Normal"))
        self.update_bug_serverity_box.setItemText(2, _translate("Dialog", "Bad"))
        self.update_bug_serverity_box.setItemText(3, _translate("Dialog", "Extreme"))
        self.update_bug_serverity_box.setItemText(4, _translate("Dialog", "EMEGENCY"))
        self.update_bug_status_box.setItemText(0, _translate("Dialog", "Working"))
        self.update_bug_status_box.setItemText(1, _translate("Dialog", "Fixed"))
        self.update_bug_status_box.setItemText(2, _translate("Dialog", "Revised"))
        self.update_bug_status_box.setItemText(3, _translate("Dialog", "Approved"))
        self.cancel_update_bug_button.setText(_translate("Dialog", "Cancel"))
        self.create_bug_serverity_box.setItemText(0, _translate("Dialog", "Small"))
        self.create_bug_serverity_box.setItemText(1, _translate("Dialog", "Normal"))
        self.create_bug_serverity_box.setItemText(2, _translate("Dialog", "Bad"))
        self.create_bug_serverity_box.setItemText(3, _translate("Dialog", "Extreme"))
        self.create_bug_serverity_box.setItemText(4, _translate("Dialog", "EMEGENCY"))
        self.label_16.setText(_translate("Dialog", "Description"))
        self.label_17.setText(_translate("Dialog", "Title"))
        self.create_bug_status_box.setItemText(0, _translate("Dialog", "Working"))
        self.create_bug_status_box.setItemText(1, _translate("Dialog", "Fixed"))
        self.create_bug_status_box.setItemText(2, _translate("Dialog", "Revised"))
        self.create_bug_status_box.setItemText(3, _translate("Dialog", "Approved"))
        self.cancel_create_bug_button.setText(_translate("Dialog", "Cancel"))
        self.confirm_create_bug_button.setText(_translate("Dialog", "Create"))
        self.label_18.setText(_translate("Dialog", "Status"))
        self.label_19.setText(_translate("Dialog", "Serverity"))
        self.create_bug_description_box.setPlainText(_translate("Dialog", "Date : \n"
"Tested by :\n"
"Cause by :\n"
"Desc on report: "))
        self.create_bug_description_box.setPlaceholderText(_translate("Dialog", "Enter the description here please"))
        self.create_bug_title_box.setPlaceholderText(_translate("Dialog", "Please do not leave blank"))
        self.label.setText(_translate("Dialog", "Bug Tracker v1"))
        self.label_2.setText(_translate("Dialog", "Our website:  "))
        self.website_button.setText(_translate("Dialog", "clickme.com"))
        self.label_3.setText(_translate("Dialog", "Support: "))
        self.email_button.setText(_translate("Dialog", "ITITIU19185@student.hcmiu.edu.vn"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
