# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_menu_admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 800)
        Dialog.setMinimumSize(QtCore.QSize(1200, 800))
        Dialog.setMaximumSize(QtCore.QSize(1200, 800))
        Dialog.setStyleSheet("QDialog#Dialog{\n"
"background-color:  rgb(125, 125, 125);\n"
"}\n"
"*{\n"
"    border : none;\n"
"    color: white;\n"
"    font: 75 10pt \"Consolas\";\n"
"}\n"
"QToolBox::tab{\n"
"    border-radius:5px;\n"
"    text-align:left;\n"
"}\n"
"\n"
"QToolBox{\n"
"    text-align: left;\n"
"    color: white;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.slide_menu_container = QtWidgets.QFrame(Dialog)
        self.slide_menu_container.setMaximumSize(QtCore.QSize(250, 16777215))
        self.slide_menu_container.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.slide_menu_container.setStyleSheet("background-color:rgb(38, 90, 92)")
        self.slide_menu_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.slide_menu_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.slide_menu_container.setObjectName("slide_menu_container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.slide_menu_container)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.slide_menu_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.header = QtWidgets.QFrame(self.frame_2)
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_6 = QtWidgets.QPushButton(self.header)
        self.pushButton_6.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../.designer/backup/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_8.addWidget(self.pushButton_6)
        self.label_4 = QtWidgets.QLabel(self.header)
        self.label_4.setStyleSheet("font: 500 italic 20pt \"Ubuntu\";\n"
"color : rgb(221, 221, 221);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.verticalLayout_6.addWidget(self.header, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.side_menu_menu = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.side_menu_menu.sizePolicy().hasHeightForWidth())
        self.side_menu_menu.setSizePolicy(sizePolicy)
        self.side_menu_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.side_menu_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_menu_menu.setObjectName("side_menu_menu")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.side_menu_menu)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.side_box = QtWidgets.QToolBox(self.side_menu_menu)
        self.side_box.setStyleSheet("font: 700 15pt \"Ubuntu\";")
        self.side_box.setObjectName("side_box")
        self.app_page = QtWidgets.QWidget()
        self.app_page.setGeometry(QtCore.QRect(0, 0, 250, 631))
        self.app_page.setObjectName("app_page")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.app_page)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame = QtWidgets.QFrame(self.app_page)
        self.frame.setMinimumSize(QtCore.QSize(20, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_13.addWidget(self.frame)
        self.app_list = QtWidgets.QListWidget(self.app_page)
        self.app_list.setStyleSheet("")
        self.app_list.setObjectName("app_list")
        self.horizontalLayout_13.addWidget(self.app_list)
        self.side_box.addItem(self.app_page, "")
        self.report_page = QtWidgets.QWidget()
        self.report_page.setGeometry(QtCore.QRect(0, 0, 250, 631))
        self.report_page.setObjectName("report_page")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.report_page)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_3 = QtWidgets.QFrame(self.report_page)
        self.frame_3.setMinimumSize(QtCore.QSize(20, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(20, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_12.addWidget(self.frame_3)
        self.staff_list = QtWidgets.QListWidget(self.report_page)
        self.staff_list.setObjectName("staff_list")
        self.horizontalLayout_12.addWidget(self.staff_list)
        self.side_box.addItem(self.report_page, "")
        self.verticalLayout_7.addWidget(self.side_box)
        self.verticalLayout_6.addWidget(self.side_menu_menu)
        self.footer = QtWidgets.QFrame(self.frame_2)
        self.footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer.setObjectName("footer")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.footer)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.signout_button = QtWidgets.QPushButton(self.footer)
        self.signout_button.setStyleSheet("font: 20pt \"Consolas\";\n"
"color : rgb(221, 221, 221);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.signout_button.setIcon(icon1)
        self.signout_button.setIconSize(QtCore.QSize(30, 30))
        self.signout_button.setObjectName("signout_button")
        self.verticalLayout_4.addWidget(self.signout_button, 0, QtCore.Qt.AlignLeft)
        self.exit_button = QtWidgets.QPushButton(self.footer)
        self.exit_button.setStyleSheet("font: 20pt \"Consolas\";\n"
"color : rgb(221, 221, 221);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_button.setIcon(icon2)
        self.exit_button.setIconSize(QtCore.QSize(30, 30))
        self.exit_button.setObjectName("exit_button")
        self.verticalLayout_4.addWidget(self.exit_button, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_6.addWidget(self.footer, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignBottom)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.slide_menu_container)
        self.main_menu_container = QtWidgets.QFrame(Dialog)
        self.main_menu_container.setStyleSheet("background-color:rgb(63, 123, 112)")
        self.main_menu_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_menu_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_menu_container.setObjectName("main_menu_container")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_menu_container)
        self.verticalLayout.setContentsMargins(3, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_frame = QtWidgets.QFrame(self.main_menu_container)
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.header_0 = QtWidgets.QFrame(self.header_frame)
        self.header_0.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_0.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_0.setObjectName("header_0")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.header_0)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.menu_button = QtWidgets.QPushButton(self.header_0)
        self.menu_button.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.menu_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_button.setIcon(icon3)
        self.menu_button.setIconSize(QtCore.QSize(25, 25))
        self.menu_button.setObjectName("menu_button")
        self.horizontalLayout_7.addWidget(self.menu_button, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.horizontalLayout_5.addWidget(self.header_0, 0, QtCore.Qt.AlignLeft)
        self.header_1 = QtWidgets.QFrame(self.header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_1.sizePolicy().hasHeightForWidth())
        self.header_1.setSizePolicy(sizePolicy)
        self.header_1.setMinimumSize(QtCore.QSize(0, 0))
        self.header_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_1.setObjectName("header_1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.header_1)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.header_1)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_6.addWidget(self.frame_4)
        self.horizontalLayout_5.addWidget(self.header_1)
        self.header_2 = QtWidgets.QFrame(self.header_frame)
        self.header_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_2.setObjectName("header_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.refresh_button = QtWidgets.QPushButton(self.header_2)
        self.refresh_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/refresh-cw.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh_button.setIcon(icon4)
        self.refresh_button.setIconSize(QtCore.QSize(20, 20))
        self.refresh_button.setObjectName("refresh_button")
        self.horizontalLayout_2.addWidget(self.refresh_button)
        self.horizontalLayout_5.addWidget(self.header_2)
        self.verticalLayout.addWidget(self.header_frame)
        self.main_menu_content = QtWidgets.QFrame(self.main_menu_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_menu_content.sizePolicy().hasHeightForWidth())
        self.main_menu_content.setSizePolicy(sizePolicy)
        self.main_menu_content.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.main_menu_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_menu_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_menu_content.setObjectName("main_menu_content")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.main_menu_content)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pager = QtWidgets.QStackedWidget(self.main_menu_content)
        self.pager.setObjectName("pager")
        self.welcome_page = QtWidgets.QWidget()
        self.welcome_page.setObjectName("welcome_page")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.welcome_page)
        self.plainTextEdit.setEnabled(False)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 0, 941, 721))
        self.plainTextEdit.setMinimumSize(QtCore.QSize(941, 0))
        self.plainTextEdit.setStyleSheet("\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pager.addWidget(self.welcome_page)
        self.app_info_page = QtWidgets.QWidget()
        self.app_info_page.setObjectName("app_info_page")
        self.label_5 = QtWidgets.QLabel(self.app_info_page)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 191, 41))
        self.label_5.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color: rgb(17, 60, 74);")
        self.label_5.setObjectName("label_5")
        self.update_app_button = QtWidgets.QPushButton(self.app_info_page)
        self.update_app_button.setGeometry(QtCore.QRect(0, 670, 171, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_app_button.sizePolicy().hasHeightForWidth())
        self.update_app_button.setSizePolicy(sizePolicy)
        self.update_app_button.setStyleSheet("background-color: rgb(246, 114, 128);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 20px;\n"
"border-color: white;\n"
"padding: 2px;\n"
"font: 700 20pt \"Ubuntu\";\n"
"color : white;")
        self.update_app_button.setObjectName("update_app_button")
        self.label_6 = QtWidgets.QLabel(self.app_info_page)
        self.label_6.setGeometry(QtCore.QRect(0, 110, 221, 51))
        self.label_6.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color:rgb(17, 60, 74);")
        self.label_6.setObjectName("label_6")
        self.info_app_staff_list = QtWidgets.QListWidget(self.app_info_page)
        self.info_app_staff_list.setGeometry(QtCore.QRect(0, 160, 471, 501))
        self.info_app_staff_list.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.info_app_staff_list.setObjectName("info_app_staff_list")
        self.info_app_name_box = QtWidgets.QLineEdit(self.app_info_page)
        self.info_app_name_box.setEnabled(False)
        self.info_app_name_box.setGeometry(QtCore.QRect(0, 50, 471, 51))
        self.info_app_name_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.info_app_name_box.setClearButtonEnabled(False)
        self.info_app_name_box.setObjectName("info_app_name_box")
        self.pager.addWidget(self.app_info_page)
        self.create_app_page = QtWidgets.QWidget()
        self.create_app_page.setObjectName("create_app_page")
        self.label_7 = QtWidgets.QLabel(self.create_app_page)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 201, 41))
        self.label_7.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color: rgb(17, 60, 74);")
        self.label_7.setObjectName("label_7")
        self.create_app_button = QtWidgets.QPushButton(self.create_app_page)
        self.create_app_button.setGeometry(QtCore.QRect(0, 670, 171, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_app_button.sizePolicy().hasHeightForWidth())
        self.create_app_button.setSizePolicy(sizePolicy)
        self.create_app_button.setStyleSheet("background-color: rgb(246, 114, 128);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 20px;\n"
"border-color: white;\n"
"padding: 2px;\n"
"font: 700 20pt \"Ubuntu\";\n"
"color : white;")
        self.create_app_button.setObjectName("create_app_button")
        self.label_8 = QtWidgets.QLabel(self.create_app_page)
        self.label_8.setGeometry(QtCore.QRect(0, 110, 201, 41))
        self.label_8.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color: rgb(17, 60, 74);")
        self.label_8.setObjectName("label_8")
        self.create_app_name_box = QtWidgets.QLineEdit(self.create_app_page)
        self.create_app_name_box.setGeometry(QtCore.QRect(0, 50, 471, 51))
        self.create_app_name_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.create_app_name_box.setObjectName("create_app_name_box")
        self.create_app_logoUrl_box = QtWidgets.QLineEdit(self.create_app_page)
        self.create_app_logoUrl_box.setGeometry(QtCore.QRect(0, 160, 471, 51))
        self.create_app_logoUrl_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.create_app_logoUrl_box.setObjectName("create_app_logoUrl_box")
        self.pager.addWidget(self.create_app_page)
        self.update_app_page = QtWidgets.QWidget()
        self.update_app_page.setObjectName("update_app_page")
        self.add_staff_to_app_button = QtWidgets.QPushButton(self.update_app_page)
        self.add_staff_to_app_button.setGeometry(QtCore.QRect(770, 670, 171, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_staff_to_app_button.sizePolicy().hasHeightForWidth())
        self.add_staff_to_app_button.setSizePolicy(sizePolicy)
        self.add_staff_to_app_button.setStyleSheet("background-color: rgb(246, 114, 128);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 20px;\n"
"border-color: white;\n"
"padding: 2px;\n"
"font: 700 20pt \"Ubuntu\";\n"
"color : white;")
        self.add_staff_to_app_button.setObjectName("add_staff_to_app_button")
        self.remove_staff_from_app_button = QtWidgets.QPushButton(self.update_app_page)
        self.remove_staff_from_app_button.setGeometry(QtCore.QRect(0, 670, 191, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_staff_from_app_button.sizePolicy().hasHeightForWidth())
        self.remove_staff_from_app_button.setSizePolicy(sizePolicy)
        self.remove_staff_from_app_button.setStyleSheet("background-color: rgb(246, 114, 128);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 18px;\n"
"border-color: white;\n"
"padding: 2px;\n"
"font: 700 20pt \"Ubuntu\";\n"
"color : white;")
        self.remove_staff_from_app_button.setObjectName("remove_staff_from_app_button")
        self.label_10 = QtWidgets.QLabel(self.update_app_page)
        self.label_10.setGeometry(QtCore.QRect(0, 110, 221, 51))
        self.label_10.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color:rgb(17, 60, 74);")
        self.label_10.setObjectName("label_10")
        self.app_staff_list = QtWidgets.QListWidget(self.update_app_page)
        self.app_staff_list.setGeometry(QtCore.QRect(0, 160, 471, 501))
        self.app_staff_list.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.app_staff_list.setObjectName("app_staff_list")
        self.label_11 = QtWidgets.QLabel(self.update_app_page)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 191, 41))
        self.label_11.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color: rgb(17, 60, 74);")
        self.label_11.setObjectName("label_11")
        self.remain_staff_list = QtWidgets.QListWidget(self.update_app_page)
        self.remain_staff_list.setGeometry(QtCore.QRect(480, 160, 461, 501))
        self.remain_staff_list.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.remain_staff_list.setObjectName("remain_staff_list")
        self.label_12 = QtWidgets.QLabel(self.update_app_page)
        self.label_12.setGeometry(QtCore.QRect(690, 100, 251, 51))
        self.label_12.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color:rgb(17, 60, 74);")
        self.label_12.setObjectName("label_12")
        self.back_to_info_app_page = QtWidgets.QPushButton(self.update_app_page)
        self.back_to_info_app_page.setGeometry(QtCore.QRect(280, 670, 191, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_to_info_app_page.sizePolicy().hasHeightForWidth())
        self.back_to_info_app_page.setSizePolicy(sizePolicy)
        self.back_to_info_app_page.setStyleSheet("background-color: rgb(246, 114, 128);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 18px;\n"
"border-color: white;\n"
"padding: 2px;\n"
"font: 700 20pt \"Ubuntu\";\n"
"color : white;")
        self.back_to_info_app_page.setObjectName("back_to_info_app_page")
        self.update_app_name_box = QtWidgets.QLineEdit(self.update_app_page)
        self.update_app_name_box.setGeometry(QtCore.QRect(0, 50, 471, 51))
        self.update_app_name_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.update_app_name_box.setObjectName("update_app_name_box")
        self.update_app_name_button = QtWidgets.QPushButton(self.update_app_page)
        self.update_app_name_button.setGeometry(QtCore.QRect(480, 670, 191, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_app_name_button.sizePolicy().hasHeightForWidth())
        self.update_app_name_button.setSizePolicy(sizePolicy)
        self.update_app_name_button.setStyleSheet("background-color: rgb(246, 114, 128);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 18px;\n"
"border-color: white;\n"
"padding: 2px;\n"
"font: 700 20pt \"Ubuntu\";\n"
"color : white;")
        self.update_app_name_button.setObjectName("update_app_name_button")
        self.pager.addWidget(self.update_app_page)
        self.staff_info_page = QtWidgets.QWidget()
        self.staff_info_page.setObjectName("staff_info_page")
        self.label_9 = QtWidgets.QLabel(self.staff_info_page)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 211, 41))
        self.label_9.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color: rgb(17, 60, 74);")
        self.label_9.setObjectName("label_9")
        self.update_staff_button = QtWidgets.QPushButton(self.staff_info_page)
        self.update_staff_button.setGeometry(QtCore.QRect(10, 670, 131, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_staff_button.sizePolicy().hasHeightForWidth())
        self.update_staff_button.setSizePolicy(sizePolicy)
        self.update_staff_button.setStyleSheet("background-color: rgb(246, 114, 128);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 20px;\n"
"border-color: white;\n"
"padding: 2px;\n"
"font: 700 20pt \"Ubuntu\";\n"
"color : white;")
        self.update_staff_button.setObjectName("update_staff_button")
        self.label_15 = QtWidgets.QLabel(self.staff_info_page)
        self.label_15.setGeometry(QtCore.QRect(0, 110, 221, 41))
        self.label_15.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color:rgb(17, 60, 74);")
        self.label_15.setObjectName("label_15")
        self.label_20 = QtWidgets.QLabel(self.staff_info_page)
        self.label_20.setGeometry(QtCore.QRect(0, 220, 111, 41))
        self.label_20.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color:rgb(17, 60, 74);")
        self.label_20.setObjectName("label_20")
        self.info_staff_email_box = QtWidgets.QLineEdit(self.staff_info_page)
        self.info_staff_email_box.setGeometry(QtCore.QRect(0, 270, 471, 51))
        self.info_staff_email_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.info_staff_email_box.setObjectName("info_staff_email_box")
        self.info_staff_fullname_box = QtWidgets.QLineEdit(self.staff_info_page)
        self.info_staff_fullname_box.setGeometry(QtCore.QRect(0, 160, 471, 51))
        self.info_staff_fullname_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.info_staff_fullname_box.setObjectName("info_staff_fullname_box")
        self.info_staff_username_box = QtWidgets.QLineEdit(self.staff_info_page)
        self.info_staff_username_box.setGeometry(QtCore.QRect(0, 50, 471, 51))
        self.info_staff_username_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.info_staff_username_box.setObjectName("info_staff_username_box")
        self.pager.addWidget(self.staff_info_page)
        self.update_staff_page = QtWidgets.QWidget()
        self.update_staff_page.setObjectName("update_staff_page")
        self.label_16 = QtWidgets.QLabel(self.update_staff_page)
        self.label_16.setGeometry(QtCore.QRect(0, 110, 221, 41))
        self.label_16.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color:rgb(17, 60, 74);")
        self.label_16.setObjectName("label_16")
        self.label_21 = QtWidgets.QLabel(self.update_staff_page)
        self.label_21.setGeometry(QtCore.QRect(0, 220, 111, 41))
        self.label_21.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color:rgb(17, 60, 74);")
        self.label_21.setObjectName("label_21")
        self.label_13 = QtWidgets.QLabel(self.update_staff_page)
        self.label_13.setGeometry(QtCore.QRect(0, 0, 211, 41))
        self.label_13.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color: rgb(17, 60, 74);")
        self.label_13.setObjectName("label_13")
        self.confirm_update_staff_button = QtWidgets.QPushButton(self.update_staff_page)
        self.confirm_update_staff_button.setGeometry(QtCore.QRect(10, 670, 131, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confirm_update_staff_button.sizePolicy().hasHeightForWidth())
        self.confirm_update_staff_button.setSizePolicy(sizePolicy)
        self.confirm_update_staff_button.setStyleSheet("background-color: rgb(246, 114, 128);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 20px;\n"
"border-color: white;\n"
"padding: 2px;\n"
"font: 700 20pt \"Ubuntu\";\n"
"color : white;")
        self.confirm_update_staff_button.setObjectName("confirm_update_staff_button")
        self.cancel_update_staff_button = QtWidgets.QPushButton(self.update_staff_page)
        self.cancel_update_staff_button.setGeometry(QtCore.QRect(150, 670, 131, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_update_staff_button.sizePolicy().hasHeightForWidth())
        self.cancel_update_staff_button.setSizePolicy(sizePolicy)
        self.cancel_update_staff_button.setStyleSheet("background-color: rgb(246, 114, 128);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 20px;\n"
"border-color: white;\n"
"padding: 2px;\n"
"font: 700 20pt \"Ubuntu\";\n"
"color : white;")
        self.cancel_update_staff_button.setObjectName("cancel_update_staff_button")
        self.label_24 = QtWidgets.QLabel(self.update_staff_page)
        self.label_24.setGeometry(QtCore.QRect(0, 330, 191, 41))
        self.label_24.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color:rgb(17, 60, 74);")
        self.label_24.setObjectName("label_24")
        self.update_staff_show_password_button = QtWidgets.QPushButton(self.update_staff_page)
        self.update_staff_show_password_button.setGeometry(QtCore.QRect(480, 400, 131, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_staff_show_password_button.sizePolicy().hasHeightForWidth())
        self.update_staff_show_password_button.setSizePolicy(sizePolicy)
        self.update_staff_show_password_button.setStyleSheet("border:2 px solid rgb(17, 60, 74);\n"
"border-radius:10px;\n"
"font: 500 italic 10pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);\n"
"background-color: rgb(85, 170, 255);")
        self.update_staff_show_password_button.setObjectName("update_staff_show_password_button")
        self.update_staff_username_box = QtWidgets.QLineEdit(self.update_staff_page)
        self.update_staff_username_box.setGeometry(QtCore.QRect(0, 50, 471, 51))
        self.update_staff_username_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.update_staff_username_box.setObjectName("update_staff_username_box")
        self.update_staff_fullname_box = QtWidgets.QLineEdit(self.update_staff_page)
        self.update_staff_fullname_box.setGeometry(QtCore.QRect(0, 160, 471, 51))
        self.update_staff_fullname_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.update_staff_fullname_box.setObjectName("update_staff_fullname_box")
        self.update_staff_password_box = QtWidgets.QLineEdit(self.update_staff_page)
        self.update_staff_password_box.setGeometry(QtCore.QRect(0, 380, 471, 51))
        self.update_staff_password_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.update_staff_password_box.setObjectName("update_staff_password_box")
        self.update_staff_email_box = QtWidgets.QLineEdit(self.update_staff_page)
        self.update_staff_email_box.setGeometry(QtCore.QRect(0, 270, 471, 51))
        self.update_staff_email_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.update_staff_email_box.setObjectName("update_staff_email_box")
        self.pager.addWidget(self.update_staff_page)
        self.create_staff_page = QtWidgets.QWidget()
        self.create_staff_page.setObjectName("create_staff_page")
        self.label_22 = QtWidgets.QLabel(self.create_staff_page)
        self.label_22.setGeometry(QtCore.QRect(0, 220, 111, 41))
        self.label_22.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color:rgb(17, 60, 74);")
        self.label_22.setObjectName("label_22")
        self.confirm_create_staff_button = QtWidgets.QPushButton(self.create_staff_page)
        self.confirm_create_staff_button.setGeometry(QtCore.QRect(10, 670, 131, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confirm_create_staff_button.sizePolicy().hasHeightForWidth())
        self.confirm_create_staff_button.setSizePolicy(sizePolicy)
        self.confirm_create_staff_button.setStyleSheet("background-color: rgb(246, 114, 128);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 20px;\n"
"border-color: white;\n"
"padding: 2px;\n"
"font: 700 20pt \"Ubuntu\";\n"
"color : white;")
        self.confirm_create_staff_button.setObjectName("confirm_create_staff_button")
        self.label_17 = QtWidgets.QLabel(self.create_staff_page)
        self.label_17.setGeometry(QtCore.QRect(0, 110, 221, 41))
        self.label_17.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color:rgb(17, 60, 74);")
        self.label_17.setObjectName("label_17")
        self.label_14 = QtWidgets.QLabel(self.create_staff_page)
        self.label_14.setGeometry(QtCore.QRect(0, 0, 211, 41))
        self.label_14.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color: rgb(17, 60, 74);")
        self.label_14.setObjectName("label_14")
        self.cancel_create_staff_button = QtWidgets.QPushButton(self.create_staff_page)
        self.cancel_create_staff_button.setGeometry(QtCore.QRect(150, 670, 131, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_create_staff_button.sizePolicy().hasHeightForWidth())
        self.cancel_create_staff_button.setSizePolicy(sizePolicy)
        self.cancel_create_staff_button.setStyleSheet("background-color: rgb(246, 114, 128);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 20px;\n"
"border-color: white;\n"
"padding: 2px;\n"
"font: 700 20pt \"Ubuntu\";\n"
"color : white;")
        self.cancel_create_staff_button.setObjectName("cancel_create_staff_button")
        self.label_23 = QtWidgets.QLabel(self.create_staff_page)
        self.label_23.setGeometry(QtCore.QRect(0, 330, 191, 41))
        self.label_23.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color:rgb(17, 60, 74);")
        self.label_23.setObjectName("label_23")
        self.create_staff_show_password_button = QtWidgets.QPushButton(self.create_staff_page)
        self.create_staff_show_password_button.setGeometry(QtCore.QRect(480, 400, 131, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_staff_show_password_button.sizePolicy().hasHeightForWidth())
        self.create_staff_show_password_button.setSizePolicy(sizePolicy)
        self.create_staff_show_password_button.setStyleSheet("border:2 px solid rgb(17, 60, 74);\n"
"border-radius:10px;\n"
"font: 500 italic 10pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);\n"
"background-color: rgb(85, 170, 255);")
        self.create_staff_show_password_button.setObjectName("create_staff_show_password_button")
        self.create_staff_username_box = QtWidgets.QLineEdit(self.create_staff_page)
        self.create_staff_username_box.setGeometry(QtCore.QRect(0, 50, 471, 51))
        self.create_staff_username_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.create_staff_username_box.setObjectName("create_staff_username_box")
        self.create_staff_fullname_box = QtWidgets.QLineEdit(self.create_staff_page)
        self.create_staff_fullname_box.setGeometry(QtCore.QRect(0, 160, 471, 51))
        self.create_staff_fullname_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.create_staff_fullname_box.setObjectName("create_staff_fullname_box")
        self.create_staff_email_box = QtWidgets.QLineEdit(self.create_staff_page)
        self.create_staff_email_box.setGeometry(QtCore.QRect(0, 270, 471, 51))
        self.create_staff_email_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.create_staff_email_box.setObjectName("create_staff_email_box")
        self.create_staff_password_box = QtWidgets.QLineEdit(self.create_staff_page)
        self.create_staff_password_box.setGeometry(QtCore.QRect(0, 380, 471, 51))
        self.create_staff_password_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.create_staff_password_box.setObjectName("create_staff_password_box")
        self.pager.addWidget(self.create_staff_page)
        self.horizontalLayout_10.addWidget(self.pager)
        self.verticalLayout.addWidget(self.main_menu_content)
        self.footer_frame = QtWidgets.QFrame(self.main_menu_container)
        self.footer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer_frame.setObjectName("footer_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.footer_frame)
        self.horizontalLayout_3.setContentsMargins(0, 4, 0, 2)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_8 = QtWidgets.QFrame(self.footer_frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_8)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_3.addWidget(self.frame_8)
        self.frame_7 = QtWidgets.QFrame(self.footer_frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_7)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2, 0, QtCore.Qt.AlignRight)
        self.website_button = QtWidgets.QPushButton(self.frame_7)
        self.website_button.setStyleSheet("color:blue;")
        self.website_button.setObjectName("website_button")
        self.horizontalLayout_4.addWidget(self.website_button, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_3.addWidget(self.frame_7)
        self.frame_9 = QtWidgets.QFrame(self.footer_frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_11.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_3 = QtWidgets.QLabel(self.frame_9)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_11.addWidget(self.label_3, 0, QtCore.Qt.AlignRight)
        self.email_button = QtWidgets.QPushButton(self.frame_9)
        self.email_button.setStyleSheet("color:blue;")
        self.email_button.setObjectName("email_button")
        self.horizontalLayout_11.addWidget(self.email_button)
        self.horizontalLayout_3.addWidget(self.frame_9)
        self.verticalLayout.addWidget(self.footer_frame, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.main_menu_container)

        self.retranslateUi(Dialog)
        self.side_box.setCurrentIndex(1)
        self.pager.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "Bug Tracker"))
        self.side_box.setItemText(self.side_box.indexOf(self.app_page), _translate("Dialog", "➤ App"))
        self.side_box.setItemText(self.side_box.indexOf(self.report_page), _translate("Dialog", "➤ Staff"))
        self.signout_button.setText(_translate("Dialog", "Sign Out"))
        self.exit_button.setText(_translate("Dialog", "Exit "))
        self.plainTextEdit.setPlainText(_translate("Dialog", "Welcome Admin"))
        self.label_5.setText(_translate("Dialog", "Name"))
        self.update_app_button.setText(_translate("Dialog", "Update App"))
        self.label_6.setText(_translate("Dialog", "Staff List"))
        self.info_app_name_box.setPlaceholderText(_translate("Dialog", "Please dont leave blank in this box!"))
        self.label_7.setText(_translate("Dialog", "Name"))
        self.create_app_button.setText(_translate("Dialog", "Create App"))
        self.label_8.setText(_translate("Dialog", "Logo Url"))
        self.create_app_name_box.setPlaceholderText(_translate("Dialog", "Please dont leave blank in this box!"))
        self.create_app_logoUrl_box.setPlaceholderText(_translate("Dialog", "Optional"))
        self.add_staff_to_app_button.setText(_translate("Dialog", "Add Staff"))
        self.remove_staff_from_app_button.setText(_translate("Dialog", "Remove Staff"))
        self.label_10.setText(_translate("Dialog", "Staff List"))
        self.label_11.setText(_translate("Dialog", "Name"))
        self.label_12.setText(_translate("Dialog", "Remain Staff"))
        self.back_to_info_app_page.setText(_translate("Dialog", "Back"))
        self.update_app_name_box.setPlaceholderText(_translate("Dialog", "Please dont leave blank in this box!"))
        self.update_app_name_button.setText(_translate("Dialog", "Update Name"))
        self.label_9.setText(_translate("Dialog", "User Name"))
        self.update_staff_button.setText(_translate("Dialog", "Update"))
        self.label_15.setText(_translate("Dialog", "Full name"))
        self.label_20.setText(_translate("Dialog", "Email"))
        self.info_staff_email_box.setPlaceholderText(_translate("Dialog", "Please dont leave blank in this box!"))
        self.info_staff_fullname_box.setPlaceholderText(_translate("Dialog", "Please dont leave blank in this box!"))
        self.info_staff_username_box.setPlaceholderText(_translate("Dialog", "Please dont leave blank in this box!"))
        self.label_16.setText(_translate("Dialog", "Full name"))
        self.label_21.setText(_translate("Dialog", "Email"))
        self.label_13.setText(_translate("Dialog", "User Name"))
        self.confirm_update_staff_button.setText(_translate("Dialog", "Update"))
        self.cancel_update_staff_button.setText(_translate("Dialog", "Cancel"))
        self.label_24.setText(_translate("Dialog", "Password"))
        self.update_staff_show_password_button.setText(_translate("Dialog", "Show Password"))
        self.update_staff_username_box.setPlaceholderText(_translate("Dialog", "Please dont leave blank in this box!"))
        self.update_staff_fullname_box.setPlaceholderText(_translate("Dialog", "Please dont leave blank in this box!"))
        self.update_staff_password_box.setPlaceholderText(_translate("Dialog", "Please dont leave blank in this box!"))
        self.update_staff_email_box.setPlaceholderText(_translate("Dialog", "Please dont leave blank in this box!"))
        self.label_22.setText(_translate("Dialog", "Email"))
        self.confirm_create_staff_button.setText(_translate("Dialog", "Create"))
        self.label_17.setText(_translate("Dialog", "Full name"))
        self.label_14.setText(_translate("Dialog", "User Name"))
        self.cancel_create_staff_button.setText(_translate("Dialog", "Cancel"))
        self.label_23.setText(_translate("Dialog", "Password"))
        self.create_staff_show_password_button.setText(_translate("Dialog", "Show Password"))
        self.create_staff_username_box.setPlaceholderText(_translate("Dialog", "Please dont leave blank in this box!"))
        self.create_staff_fullname_box.setPlaceholderText(_translate("Dialog", "Please dont leave blank in this box!"))
        self.create_staff_email_box.setPlaceholderText(_translate("Dialog", "Please dont leave blank in this box!"))
        self.create_staff_password_box.setPlaceholderText(_translate("Dialog", "Please dont leave blank in this box!"))
        self.label.setText(_translate("Dialog", "Bug Tracker v1"))
        self.label_2.setText(_translate("Dialog", "Our website:  "))
        self.website_button.setText(_translate("Dialog", "clickme.com"))
        self.label_3.setText(_translate("Dialog", "Support: "))
        self.email_button.setText(_translate("Dialog", "ITITIU19185@student.hcmiu.edu.vn"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
