# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'report_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 800)
        Dialog.setMinimumSize(QtCore.QSize(1200, 800))
        Dialog.setMaximumSize(QtCore.QSize(1200, 800))
        self.backgournd_frame = QtWidgets.QFrame(Dialog)
        self.backgournd_frame.setGeometry(QtCore.QRect(0, 0, 1201, 801))
        self.backgournd_frame.setStyleSheet("background-color: rgb(63, 123, 112)")
        self.backgournd_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.backgournd_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.backgournd_frame.setObjectName("backgournd_frame")
        self.report_button = QtWidgets.QPushButton(self.backgournd_frame)
        self.report_button.setGeometry(QtCore.QRect(1090, 746, 94, 41))
        self.report_button.setStyleSheet("background-color: rgb(246, 114, 128);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 10px;\n"
"border-color: white;\n"
"padding: 2px;\n"
"font: 700 20pt \"Ubuntu\";\n"
"color : white;")
        self.report_button.setObjectName("report_button")
        self.title_box = QtWidgets.QLineEdit(self.backgournd_frame)
        self.title_box.setGeometry(QtCore.QRect(10, 70, 1061, 41))
        self.title_box.setStyleSheet("border-bottom:3px solid rgb(17, 60, 74);\n"
"border-radius:1px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.title_box.setText("")
        self.title_box.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.title_box.setObjectName("title_box")
        self.label = QtWidgets.QLabel(self.backgournd_frame)
        self.label.setGeometry(QtCore.QRect(10, 20, 91, 51))
        self.label.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color: rgb(17, 60, 74);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.backgournd_frame)
        self.label_2.setGeometry(QtCore.QRect(10, 150, 221, 51))
        self.label_2.setStyleSheet("font: 500 italic 30pt \"Ubuntu\";\n"
"color:rgb(17, 60, 74);")
        self.label_2.setObjectName("label_2")
        self.cancel_button = QtWidgets.QPushButton(self.backgournd_frame)
        self.cancel_button.setGeometry(QtCore.QRect(1090, 10, 101, 41))
        self.cancel_button.setStyleSheet("background-color: rgb(246, 114, 128);\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 10px;\n"
"border-color: white;\n"
"padding: 2px;\n"
"font: 700 20pt \"Ubuntu\";\n"
"color : white;")
        self.cancel_button.setObjectName("cancel_button")
        self.description_box = QtWidgets.QPlainTextEdit(self.backgournd_frame)
        self.description_box.setGeometry(QtCore.QRect(10, 200, 1071, 591))
        self.description_box.setStyleSheet("border:3px solid rgb(17, 60, 74);\n"
"border-radius:20px;\n"
"font: 500 italic 20pt \"Ubuntu\";\n"
"color: rgb(221, 221, 221);")
        self.description_box.setObjectName("description_box")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.report_button.setText(_translate("Dialog", "Report"))
        self.title_box.setPlaceholderText(_translate("Dialog", "Enter Your Title Here ..."))
        self.label.setText(_translate("Dialog", "Title"))
        self.label_2.setText(_translate("Dialog", "Description"))
        self.cancel_button.setText(_translate("Dialog", "Cancel"))
        self.description_box.setPlaceholderText(_translate("Dialog", "Enter your description about the bug you found..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
